export type { ApiResponse, JSendStatus, PaginatedResponse } from './common';
export type { LoginInput, LoginResponse } from './auth';
export type {
  User,
  StaffAccountCreateInput,
  StaffAccountUpdateInput,
  StaffDirectoryEntry,
  CurrentUserProfile,
  CurrentUserProfileUpdateInput,
  ChangePasswordInput,
} from './user';
export type {
  SuperAdmin,
  SuperAdminCreateInput,
  AssignRootAccountInput,
  TenantRootAdmin,
} from './superadmin';
export type {
  University,
  UniversityCreateInput,
  PublicTenantProfile,
  UniversitySettings,
  UniversityAnalytics,
  UniversityAnalyticsAttendance,
  UniversityAnalyticsAttendanceWindow,
  UniversityAnalyticsAbsenceLevel,
  UniversityAnalyticsCommunications,
  UniversityAnalyticsFacultyBreakdown,
  UniversityAnalyticsItem,
  UniversityAnalyticsProgramAbsence,
  UniversityAnalyticsProgramBreakdown,
  UniversityAnalyticsResources,
  UniversityAnalyticsSummary,
} from './university';
export type { Announcement, AnnouncementInput } from './announcement';
export type {
  CreateLearningGroupPostInput,
  LearningGroupAttachment,
  LearningGroupComment,
  LearningGroupCourse,
  LearningGroupDetails,
  LearningGroupMember,
  LearningGroupPost,
  LearningGroupPostPage,
  LearningGroupPostType,
  LearningGroupRole,
  LearningGroupSummary,
} from './learning-group';
export type {
  AiChatRequest,
  AiChatResponse,
  AiExamResponse,
  AiHealth,
  AiIndexInfo,
  AiHistoryMessage,
  AiMindMapResponse,
  AiProjectChapters,
  AiProjectFiles,
  AiSearchResponse,
  AiSession,
  AiSessionHistory,
  AiSessionList,
  AiStudyData,
  AiStudyFiles,
  AiSummaryResponse,
  AiSyncResult,
} from './ai';
export type {
  StudentTranscripts,
  TranscriptBatchGenerationSummary,
  TranscriptCourse,
  TranscriptGenerationJob,
  TranscriptGenerationJobResult,
  TranscriptGenerationJobResultItem,
  TranscriptGenerationJobStatus,
  TranscriptRecord,
  TranscriptSemesterInfo,
} from './transcript';
export type { Faculty, FacultyCreateInput, FacultyUpdateInput, FacultyRegulation } from './faculty';
export type {
  Program,
  ProgramCreateInput,
  ProgramUpdateInput,
  ProgramType,
  ResultDisplayType,
  BlockReasonType,
  FeeType,
  ProgramLevel,
  ProgramLevelInput,
  ProgramFee,
  ProgramFeeInput,
  ProgramTranscriptDefinition,
  ProgramTranscriptDefinitionInput,
  AcademicLoadSemester,
  AcademicLoadSemesterInput,
  AcademicLoadGPA,
  AcademicLoadGPAInput,
} from './program';
export type {
  AssignCourseAssessmentInput,
  Course,
  CourseAssessment,
  CourseAssessmentType,
  CreateCourseAssessmentInput,
  CourseCreateInput,
  CourseStudentGrade,
  CourseStudentGrades,
  CourseUpdateInput,
  CourseType,
  CoursePrerequisite,
  UpdateCourseAssessmentInput,
  UpdateStudentGradeInput,
} from './course';
export type {
  Classroom,
  ClassroomCreateInput,
  ClassroomUpdateInput,
  ClassroomType,
  ClassSessionSummary,
} from './classroom';
export type {
  DayOfWeek,
  TimetableCourseLookup,
  TimetableClassroomLookup,
  TimetableStaffLookup,
  ScheduleSlot,
  GetScheduleResponse,
  TimetableSaveSessionInput,
  TimetableSaveLevelInput,
  TimetableSaveResult,
} from './schedule';
export type { Semester, SemesterCreateInput, SemesterUpdateInput } from './semester';
export type {
  AttendanceCourseOption,
  AttendanceCourseSummary,
  AttendanceDashboardData,
  DashboardClassroom,
  DashboardCourse,
  AttendanceSession,
  AttendanceSessionRecord,
  CreateAttendanceSessionDto,
  EnrolledStudent,
  MobileTimetableData,
  MobileTimetableItem,
  StaffAttendanceCourse,
  StaffDashboardData,
  StaffDashboardScheduleItem,
  StudentDashboardCreditSegment,
  StudentDashboardData,
  StudentDashboardScheduleItem,
  StudentAttendanceStatus,
  StudentAttendanceTimelineItem,
  UpsertAttendancesDto,
} from './attendance';
export type { Role, RoleCreateInput, Permission } from './rbac';
export type {
  StudentStatus,
  StudentGender,
  StudentReligion,
  StudentSortOrder,
  StudentRecord,
  StudentListQuery,
  StudentListPagination,
  StudentListResponse,
  CreateStudentInput,
  UpdateStudentInput,
  StudentImportRequest,
  StudentImportStartResponse,
  StudentImportErrorRow,
  StudentImportStatus,
  StudentImportStatusResponse,
  StudentWriteResponse,
} from './student';
export type {
  EnrollmentSubmitInput,
  EnrollmentScheduleSlot,
  EnrollmentSubmitResponse,
  EnrollmentJobStatus,
  EnrollmentJobSlotResult,
  EnrollmentJobResult,
  EnrollmentStatusResponse,
  AdminEnrollmentStatus,
  AdminEnrollmentRecord,
  AdminEnrollmentSlotOption,
  AdminEnrollmentListQuery,
  AdminEnrollmentListResponse,
  AdminEnrollmentOptionsResponse,
  AdminEnrollmentStudentTrackResponse,
  AdminEnrollmentCreateInput,
  AdminEnrollmentUpdateInput,
} from './enrollment';
export type {
  EnrollmentWindowLookupQuery,
  EnrollmentWindowPayload,
  EnrollmentWindowRecord,
} from './enrollment-window';
