export { AuthService } from './modules/auth/auth.service';
export { UniversityService } from './modules/university/university.service';
export { SuperAdminService } from './modules/superadmin/superadmin.service';
export { UserService } from './modules/user/user.service';
export { CourseService } from './modules/course/course.service';
export { ClassroomService } from './modules/classroom/classroom.service';
export { AttendanceService } from './modules/attendance/attendance.service';
export { FacultyService } from './modules/faculty/faculty.service';
export { SemesterService } from './modules/semester/semester.service';
export { ProgramService } from './modules/program/program.service';
export { RBACService } from './modules/rbac/rbac.service';
export { StudentService } from './modules/student/student.service';
export { ScheduleService } from './modules/Schedule/schedule.service';
export { EnrollmentService } from './modules/enrollment/enrollment.service';

export { apiClient } from './client';

export type {
  ApiResponse,
  JSendStatus,
  LoginInput,
  LoginResponse,
  User,
  SuperAdmin,
  SuperAdminCreateInput,
  AssignRootAccountInput,
  University,
  UniversityCreateInput,
  PublicTenantProfile,
  Faculty,
  FacultyCreateInput,
  FacultyUpdateInput,
  Program,
  ProgramCreateInput,
  ProgramUpdateInput,
  ProgramType,
  ResultDisplayType,
  BlockReasonType,
  FeeType,
  ProgramLevel,
  ProgramLevelInput,
  ProgramFee,
  ProgramFeeInput,
  ProgramTranscriptDefinition,
  ProgramTranscriptDefinitionInput,
  AcademicLoadSemester,
  AcademicLoadSemesterInput,
  AcademicLoadGPA,
  AcademicLoadGPAInput,
  Course,
  CourseCreateInput,
  CourseUpdateInput,
  CourseType,
  CoursePrerequisite,
  Classroom,
  ClassroomCreateInput,
  ClassroomUpdateInput,
  ClassroomType,
  ClassSessionSummary,
  DayOfWeek,
  TimetableCourseLookup,
  TimetableClassroomLookup,
  TimetableStaffLookup,
  ScheduleSlot,
  TimetableSaveSessionInput,
  TimetableSaveLevelInput,
  TimetableSaveResult,
  Semester,
  SemesterCreateInput,
  SemesterUpdateInput,
  Role,
  RoleCreateInput,
  Permission,
  StaffAccountCreateInput,
  StaffAccountUpdateInput,
  StaffDirectoryEntry,
  StudentStatus,
  StudentGender,
  StudentReligion,
  StudentSortOrder,
  StudentRecord,
  StudentListQuery,
  StudentListPagination,
  StudentListResponse,
  CreateStudentInput,
  UpdateStudentInput,
  StudentImportRequest,
  StudentImportStartResponse,
  StudentImportErrorRow,
  StudentImportStatus,
  StudentImportStatusResponse,
  StudentWriteResponse,
  EnrollmentSubmitInput,
  EnrollmentScheduleSlot,
  EnrollmentSubmitResponse,
  EnrollmentJobStatus,
  EnrollmentJobSlotResult,
  EnrollmentJobResult,
  EnrollmentStatusResponse,
} from './types/index';
